Add dict_replace_if_equal command to buildozer.
bazelbuild/buildtools pull request #1274
Opened 2024-05-31 20:01 UTC by tsell

This is useful for making modifications at scale, where you only want to replace certain dictionary values. To illustrate, suppose you have a BUILD file containing many targets, some of which use some "old_value" which you wish to replace with "new_value" in a dictionary, and some of which use other values that you don't want to modify:

```
macro(
  name = "foo",
  macro_values = {
    "key": "old_value",
  },
)

macro(
  name = "bar",
  macro_values = {
    "key": "neutral_value",
  },
)
```

With this new command, these can all be modified like so:
```
buildozer "dict_replace_if_equal macro_values key old_value new_value" //path/to/these/targets:*
```

Resulting in the desired change:
```
macro(
  name = "foo",
  macro_values = {
    "key": "new_value",
  },
)

macro(
  name = "bar",
  macro_values = {
    "key": "neutral_value",
  },
)
```

2024-06-05 15:08 UTC, vladmos requested changes
Thanks!

2024-06-06 18:35 UTC, tsell commented on edit/buildozer.go
> +		if labels.Equal(e.Value, oldV, env.Pkg) || e.Value == oldV {
Done.

2024-06-06 18:35 UTC, tsell commented on edit/buildozer_test.go
> +
Done.

2024-06-07 19:36 UTC, tsell reviewed
Done

2024-06-26 16:13 UTC, vladmos approved these changes

2024-06-26 16:13 UTC, merged