Add rules_shell fixing
bazelbuild/buildtools pull request #1303
Opened 2024-10-17 23:13 UTC by keith

Currently these are split into 3 rules because 1 rule cannot add 3 load
statements and this repo doesn't have a defs.bzl that exposes them all

2024-10-17 23:14 UTC, keith commented
i don't feel strongly about the defs.bzl part since realistically these rules shouldn't be disabled, but happy to try to go that route and add that upstream to unify this into 1 rule

2025-01-10 21:04 UTC, keith commented
@vladmos @comius another one for you, CI issue is infra

2025-01-13 11:12 UTC, comius requested changes
Thanks for this change!

2025-01-13 11:12 UTC, comius commented on warn/warn_bazel_api.go
> +	return NotLoadedFunctionUsageCheck(f, fileReader, []string{"sh_binary"}, "@rules_shell//shell:sh_binary.bzl")
Can you move hard coded  "@rules_shell//shell:" into tables. See other warnings.

This makes it a bit easier to import, because we're overriding those labels internally.

2025-01-13 12:25 UTC, comius commented
cc @c-mita

2025-01-13 18:11 UTC, keith commented on warn/warn_bazel_api.go
> +	return NotLoadedFunctionUsageCheck(f, fileReader, []string{"sh_binary"}, "@rules_shell//shell:sh_binary.bzl")
ah nice, i skipped that not knowing you were replacing that internally, i should have known! Updated!

2025-01-17 12:45 UTC, vladmos approved these changes

2025-01-17 12:49 UTC, merged